# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='ambiente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambientes.Ambiente'),
            preserve_default=False,
        ),
    ]
