# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20170910_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
